openapi: 3.0.3
info:
    title: Lumen
    description: ''
    version: 1.0.0
servers:
    -
        url: 'http://localhost'
paths:
    /:
        get:
            summary: ''
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: ''
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: 'Lumen (8.2.3) (Laravel Components ^8.0)'
            tags:
                - Endpoints
            security: []
    /v1/users:
        get:
            summary: Read
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                401:
                    description: ''
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: Unauthorized.
            tags:
                - Endpoints
            security: []
        post:
            summary: 'Criar usuário'
            description: 'Cria um usuário.'
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Usuarios
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                api_token:
                                    type: string
                                    description: 'Token do usuário'
                                    example: b71175dd5644180d4bce21d1790bb0cf-eccbc87e4b5ce2fe28308fd9f2a7baf3
                                id:
                                    type: integer
                                    description: 'ID do usuário'
                                    example: 1
                            required:
                                - api_token
                                - id
            security: []
        put:
            summary: 'Atualizar usuario'
            description: 'Atualiza os dados de um usuário'
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200, success'
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: "{\n     \"id\": 1,\n     \"name\": \"Ronierison Sena\"\n     \"email\": \"teste@teste.com\"\n     [...]\n}"
                404:
                    description: '404, user not found'
                    content:
                        application/json:
                            schema:
                                type: object
                                example:
                                    message: 'usuário não encontrado.'
                                properties:
                                    message: { type: string, example: 'usuário não encontrado.' }
            tags:
                - Usuarios
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                id:
                                    type: integer
                                    description: 'ID do usuário'
                                    example: 19
                            required:
                                - id
    '/v1/users/{id}':
        delete:
            summary: Delete
            description: ''
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses: {  }
            tags:
                - Endpoints
            security: []
        parameters:
            -
                in: path
                name: id
                description: ''
                example: aut
                required: true
                schema:
                    type: string
    /v1/login:
        post:
            summary: Login
            description: "Faz o login do usuario\nSe email e senha coincidirem, gera um md5 da data concatenando com o ID do usuário\ne salva no campo api_token com o tempo definido no arquivo .env TIME_TO_RESET_TOKEN"
            parameters:
                -
                    in: header
                    name: Content-Type
                    description: ''
                    example: application/json
                    schema:
                        type: string
                -
                    in: header
                    name: Accept
                    description: ''
                    example: application/json
                    schema:
                        type: string
            responses:
                200:
                    description: '200'
                    content:
                        text/plain:
                            schema:
                                type: string
                                example: string
            tags:
                - Usuarios
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                login:
                                    type: string
                                    description: 'Email do usuário'
                                    example: praesentium
                                password:
                                    type: string
                                    description: 'Senha do usuário'
                                    example: excepturi
                            required:
                                - login
                                - password
            security: []
